pipeline {
    agent any

    stages {
        stage('Start') {
            steps {
                echo 'Ola mundo!'
            }
        }
        stage('criando a imagem'){
            steps{
                script{
                    dockerapp = docker.build("italopessan/api-jenkins:latest", "-f ./teste-jenkins/Dockerfile .")
                }
            }
        }
    }
}
