pipeline {
    agent any

    stages {
        stage('Start') {
            steps {
                echo 'Ola mundo!'
            }
        }
        stage{
            steps{
                script{
                    dockerapp = docker.build("italopessan/api-jenkins:latest",".")
                }
            }
        }
    }
}
