pipeline {
    agent any

    stages {
        stage('Start') {
            steps {
                echo 'Ola mundo!'
            }
        }
        stage('criando a imagem'){
            steps{
                script{
                    dockerapp = docker.build("italopessan/api-jenkins:latest" .)
                }
            }
        }// C:\Users\italo\OneDrive\Área de Trabalho\Projetos\teste-jenkins\teste-jenkins\teste-jenkins\Dockerfile  teste-jenkins\teste-jenkins\Jenkinsfile
    }
}
